M48
; DRILL file {KiCad 9.0.4} date 2025-11-06T03:01:43+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-06T03:01:43+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X106.32Y-59.64
X106.32Y-106.59
X130.83Y-59.64
X130.83Y-106.59
M30
