M48
; DRILL file {KiCad 9.0.4} date 2025-11-06T19:22:00+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-06T19:22:00+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X78.035Y-61.48
X78.035Y-108.43
X102.545Y-61.48
X102.545Y-108.43
M30
