// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnYzjaaWZReHSNAfV0jMKdrYPHN9Qfg04',
    appId: '1:677604496425:web:626ec3fdda3a419aa83838',
    messagingSenderId: '677604496425',
    projectId: 'sensor-hub-91866',
    authDomain: 'sensor-hub-91866.firebaseapp.com',
    databaseURL: 'https://sensor-hub-91866-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-hub-91866.firebasestorage.app',
    measurementId: 'G-EHG0TBXS1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe7JnySnrusXezjfLlNgU-SKPet9HgU3I',
    appId: '1:677604496425:android:81e9c9a00691d52ca83838',
    messagingSenderId: '677604496425',
    projectId: 'sensor-hub-91866',
    databaseURL: 'https://sensor-hub-91866-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-hub-91866.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmnH2n0mD4NShwuZmDnQ-gJv1CzzVmai0',
    appId: '1:677604496425:ios:3f5148c58919d115a83838',
    messagingSenderId: '677604496425',
    projectId: 'sensor-hub-91866',
    databaseURL: 'https://sensor-hub-91866-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-hub-91866.firebasestorage.app',
    androidClientId: '677604496425-7l0qi2m091bnvmao3nhd758sr0aeih2v.apps.googleusercontent.com',
    iosClientId: '677604496425-o9lm3gitv9mig25q10otu6qah7ji7fc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.graappNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmnH2n0mD4NShwuZmDnQ-gJv1CzzVmai0',
    appId: '1:677604496425:ios:3f5148c58919d115a83838',
    messagingSenderId: '677604496425',
    projectId: 'sensor-hub-91866',
    databaseURL: 'https://sensor-hub-91866-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-hub-91866.firebasestorage.app',
    androidClientId: '677604496425-7l0qi2m091bnvmao3nhd758sr0aeih2v.apps.googleusercontent.com',
    iosClientId: '677604496425-o9lm3gitv9mig25q10otu6qah7ji7fc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.graappNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnYzjaaWZReHSNAfV0jMKdrYPHN9Qfg04',
    appId: '1:677604496425:web:4a0bee515cb901c7a83838',
    messagingSenderId: '677604496425',
    projectId: 'sensor-hub-91866',
    authDomain: 'sensor-hub-91866.firebaseapp.com',
    databaseURL: 'https://sensor-hub-91866-default-rtdb.firebaseio.com',
    storageBucket: 'sensor-hub-91866.firebasestorage.app',
    measurementId: 'G-ZBPPBE3SVD',
  );
}
